name: IIS Deploy
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.18.0"

      - name: Install Dependencies
        run: npm install

      - name: Run Lint
        run: npm run lint

      - name: Build Project
        run: npm run build

      - name: Deploy to IIS
        shell: powershell
        run: |
          Import-Module WebAdministration

          # 1. App Pool leállítása
          Stop-WebAppPool -Name "Petrik1" -ErrorAction SilentlyContinue

          # 2. Várjunk egy kicsit a fájlzárolások miatt
          Start-Sleep -s 2

          # 3. MÁSOLÁS - Itt a ./dist/* a lényeg!
          # A -Force felülírja a régi fájlokat
          Copy-Item -Path "./dist/*" -Destination "C:\Users\Administrator\Desktop\Petrik1\dist" -Recurse -Force

          # 4. App Pool újraindítása
          Start-WebAppPool -Name "Petrik1"
